##
# Builds and publishes tags for releases.
# The release tag will be updated to a new commit that
# only contains the built code.
##
name: Release

# Manual or automatic release
on:
  release:
    types: [published, edited]

jobs:
  build:
    name: Build and Tag
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Install deps and build
        run: npm ci && npm run build

      # Force push major and minor tags, e.g. v1, v1.0
      # See documentation: https://github.com/JasonEtco/build-and-tag-action
      - uses: JasonEtco/build-and-tag-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
